name: Update Tag Description
on:
  push:
    tags:
      - 'v*'

jobs:
  get_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all commits

      - name: Get the last two tags
        id: last_two_tags
        run: |
          git fetch --tags
          git tag --sort=-creatordate
          tags=$(git tag --sort=-creatordate)
          
          tags_array=($tags)
          first_tag=${tags_array[0]}
          echo "First Tag: $first_tag"
          second_tag=${tags_array[1]}
          echo "Second Tag: $second_tag"
          sixt_tag=${tags_array[6]}
          echo "Third Tag: $sixt_tag"
          
          last_two_tags=($(echo "$tags" | head -n 2))
          echo "PENULTIMATE_TAG=$last_two_tags[1]" >> $GITHUB_ENV
          echo "LAST_TAGS=$last_two_tags[0]" >> $GITHUB_ENV
          IFS=$'\n' read -ra tags_array <<< "$tags"
          for tag in "${tags_array[@]}"; do
            echo "Tag: $tag"
          done
          echo "PENULTIMATE_TAG=$PENULTIMATE_TAG"
          echo "LAST_TAG=$LAST_TAG"
          
  
      - name: Generate Changelog
        id: generate_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install conventional-changelog-cli
          npm install -g conventional-changelog-cli
          
          penultimate_tag=${{ env.PENULTIMATE_TAG }}
          last_tag=${{ env.LAST_TAG }}
          
          if [ "$penultimate_tag" == "" ]; then
          conventional-changelog -p angular -o CHANGELOG.md -r 0...$last_tag
          else
            conventional-changelog -p angular -o CHANGELOG.md -r $penultimate_tag..$last_tag
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: './CHANGELOG.md'
          retention-days: 5
          if-no-files-found: error

