name: Update Tag Description
on:
  push:
    tags:
      - 'v*'

jobs:
  get_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all commits

      - name: Get the last two tags
        id: last_two_tags
        run: |
          git fetch --tags
          tags=$(git tag --sort=-creatordate)  
          tags_array=($tags)  
          last_tag_hash=$(git rev-parse ${tags_array[0]})
          penultimate_tag_hash=$(git rev-parse ${tags_array[1]})
          echo "LAST_TAGS=$last_tag_hash" >> $GITHUB_ENV
          echo "PENULTIMATE_TAG=$penultimate_tag_hash" >> $GITHUB_ENV
  
      - name: Generate Changelog
        id: generate_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install conventional-changelog-cli
          npm install -g conventional-changelog-cli
          
          penultimate_tag=${{ env.PENULTIMATE_TAG }}
          last_tag=${{ env.LAST_TAG }}
          
          if [ "$penultimate_tag" == "" ]; then
          conventional-changelog -p angular -o CHANGELOG.md -r
          else
            conventional-changelog -p angular -o CHANGELOG.md -r $penultimate_tag..$last_tag
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: './CHANGELOG.md'
          retention-days: 5
          if-no-files-found: error

