name: Update Tag Description
on:
  push:
    tags:
      - 'v*'

jobs:
  get_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all commits

      - name: Get the last two tags
        id: last_two_tags
        run: |
          git fetch --tags
          tags=$(git tag --sort=-creatordate)
          last_two_tags=($(echo "$tags" | head -n 2))
          echo "PENULTIMATE_TAG=$last_two_tags[1]" >> $GITHUB_ENV
          echo "LAST_TAGS=$last_two_tags[0]" >> $GITHUB_ENV
  
      - name: Generate Changelog
        id: generate_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install conventional-changelog-cli
          npm install -g conventional-changelog-cli
          
          penultimate_tag=${{ env.PENULTIMATE_TAG }}
          last_tag=${{ env.LAST_TAG }}
          
          if [ "$penultimate_tag" == "" ]; then
          # changelog=$(conventional-changelog -p angular -r 0...$last_tag)
          conventional-changelog -o CHANGELOG.md -r 0...$last_tag
          else
            conventional-changelog -o CHANGELOG.md -r $penultimate_tag..$last_tag
            # changelog=$(conventional-changelog -p angular -r $penultimate_tag..$last_tag)
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: './CHANGELOG.md'
          
      # Add the new step to list repository contents
      - name: List repository contents
        run: ls -R
